version: '3.7'
services:
  nginx:
    build:
      context: ets/nginx
    container_name: nginx_rest
    volumes:
    - ./ets/nginx/hosts:/etc/nginx/conf.d
    - ./logs:/var/log/nginx
    - ./app:/var/www
    ports:
    - "80:80"
    links:
      - php
  php:
    build:
      context: ets/php
      dockerfile: Dockerfile
    links:
      - db
    volumes:
    - ./app/:/var/www
    container_name: php_rest
    restart: unless-stopped
    tty: true
  db:
    image: mysql:5.7
    container_name: mysql_rest
    ports:
    - 3306:3306
    volumes:
    - ./ets/dbdata:/var/lib/mysql/
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    tty: true
    environment:
      MYSQL_ROOT_PASSWORD: root